### ISSUE TITLE
Unable to open settings UI anymore

### ISSUE THREAD

**Issue by Altair31** [SheepGoMeh/VisibilityPlugin#11]
I'm currently not able to see the configuration interface, neither through Plugin installer, neither through /pvis command
I suspect it to be offscreen but I did not find a way to reset the position.
Macro works fine, but if I want to check the status, I'm doomed.

**Comment by SheepGoMeh** [comment]
Please refer to the Dalamud FAQ [here](https://goatcorp.github.io/faq/dalamud_troubleshooting#q-how-do-i-reset-dalamudplugin-window-locations)

**Comment by Altair31** [comment]
Thanks, it is fixed
