### ISSUE TITLE
Hotkey to toggle player visibility

### ISSUE THREAD

**Issue by gamer4eg** [SheepGoMeh/VisibilityPlugin#16]
Add hotkey to toggle player visibility (or comand for macro) .
Example: This is needed in Bozja raids, so that the gamers do not interfere with clicking on the chest.

**Comment by SheepGoMeh** [comment]
1. Visibility will never work in duties
2. `/pvis help` gives you all the usable commands.

Please read the documentation before opening such issues, thank you.

**Comment by gamer4eg** [comment]
My bad, sorry for false issue...
I found comand
`/pvis hideplayer toggle`
