### ISSUE TITLE
Option to hide 21+ until 1-20 completed

### ISSUE THREAD

**Issue by kaedys** [SheepGoMeh/VisibilityPlugin#19]
I know it's probably a transient issue for any given user, but it'd be nice if there was an option under visibility (possibly toggled on by default) that would not display vistas beyond 20 until the first 20 were completed (and the unlock quest in Gridania completed, if that can be checked by a plugin).  Personally, I definitely tried at least a dozen or so vistas beyond that point before learning of the "must do first 20" rule.  There's a help dropdown, but I feel it's not as obvious as it could be, and being able to entirely suppress visibility for them would help, imo, especially if it were on by default.  I know I sometimes open the list and go "oh, vista up!...oh, nvm, it's number [53 or w/e]", because I've still not quite completed those initial 20 (I tend to do them opportunistically, often when reminded by a vista orb, rather than as a dedicated hunt).

**Comment by Lynnea1320** [comment]
I think that's the Tourist plugin, not this one, that handles ARR vistas.

**Comment by kaedys** [comment]
I...have no idea how I ended up posting this on this plugin instead of Tourist.  Er...oops.
