### ISSUE TITLE
Option to hide housing items/retainers

### ISSUE THREAD

**Issue by Zlkva** [SheepGoMeh/VisibilityPlugin#20]
Hey there,

I love your plugin. I have a FC mate that insists upon putting items over/in the way/etc of portions of our FC house. I was wondering if there was a way for you to add the ability to hide retainers or other such housing items. 

I realize this may be a request specific to me, I'm ok with building the project myself I just am wondering if you can help me add this feature to your codebase for my specific build.

Thanks! Appreciate your plugin otherwise!

**Comment by SheepGoMeh** [comment]
Please refer to #10
