### ISSUE TITLE
Expansion of "Hide non-party Earthly Star"

### ISSUE THREAD

**Issue by torakiti2017** [SheepGoMeh/VisibilityPlugin#23]
In addition to "Earthly Star", I would like to see additional settings for "Asylum" and "Sacred Soil".

**Comment by Felys1998** [comment]
Those are already hidden if you turn off non-party effects.

**Comment by torakiti2017** [comment]
Is it the battle effect setting of the character config?
If you change that setting, the usefulness of "Hide non-party Earthly Star" of this plug-in will be lost.
I think the "Hide non-party Earthly Star" setting of this plug-in is intended for people who have "display" or "simple display" for non-party effects.
(For example, you want to hide the "Earthly Star" display of another alliance at an alliance party)

**Comment by SheepGoMeh** [comment]
[Please refer to this](https://www.reddit.com/r/ffxiv/comments/8shmse/comment/e0zf339/?utm_source=share&utm_medium=web2x&context=3)
