### ISSUE TITLE
Needs Update 6.0

### ISSUE THREAD

**Issue by DiggityMan420** [SheepGoMeh/VisibilityPlugin#25]
No showing up as updated to 6.0 and plans to do so?

**Comment by kgetit** [comment]
I would like to add to this request. This addon is amazing (especially around Limsa).

**Comment by Xelfen** [comment]
I have already made a request for this.

**Comment by KODETTO** [comment]
I noticed that the plugin author (@SheepGoMeh) has been active on the XLPlugins repository in the past couple days. I optimistically assume this is related to updating VisibilityPlugin for 6.0

**Comment by stuffinhere** [comment]
Mind giving us the link? The only XLplugins I find is some Indian company.

**Comment by Hezkezl** [comment]
> Mind giving us the link? The only XLplugins I find is some Indian company.

it's just the default XIVLauncher plugins list. This repo's been updated and works now, so you could also install from here too.
