### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by V3semir** [SheepGoMeh/VisibilityPlugin#26]
Hello! Is it possible to add an option to send an alert if the specific person is near us or on the same map? I have a friend who would feel safer to know if their stalker is near them, and they are not comfortable voidlisting them entirely. I'd be really grateful if this feature could be implemented.

**Comment by kgetit** [comment]
The request you ask is a radar and I think it falls close to cheating since it can be used for other activities. But, you should look into **Peeping Tom** plugin.

**Comment by Xelfen** [comment]
I don't see how it's cheating to simply avoid stalkers (who have no business being in an mmorpg), I hope your friend finds a way to avoid it, if it helps the moderation conditions have greatly improved concerning harassment.

I also have another idea, PlayerTrack has just been updated to be compatible with Visiblity's blacklist, I'm not sure how it works but I think it's close to your request
