### ISSUE TITLE
Can't open the config window

### ISSUE THREAD

**Issue by dovochi** [SheepGoMeh/VisibilityPlugin#28]
Since yesterday, I can't open the config window for some reason. I tried clicking the config icon in the plug in list as well as typing /pvis and nothing showed up on either of my monitors. I tried looking around the edges of the monitors to see if the window is hiding somewhere but I don't see it at all. This happens to only this plug in, while others are fine and I can still open their config windows. I tried disabling then re-enabling Visibility on the plug in list, as well as disabling multi-monitor support in Dalamud but that didn't help. The plug in is working otherwise, though. It's still hiding all players, chocobos and minions as per the previous settings, albeit after a few seconds of delay after I teleported into the zone. Is there anything I can try on my end to fix it?

Edit: The /void command in chat is still working.

**Comment by SheepGoMeh** [comment]
Please refer to #11

**Comment by dovochi** [comment]
It's working now. Thanks so much!
