### ISSUE TITLE
Whitelist eureka&bozja?

### ISSUE THREAD

**Issue by Bluefissure** [SheepGoMeh/VisibilityPlugin#3]
Is it okay to add eureka and bozja to the [territory whitelist](https://github.com/SheepGoMeh/VisibilityPlugin/blob/master/Visibility/Configuration/VisibilityConfiguration.cs#L193)?
Some users complain about too many ppl in CE causes the game lagging seriously.

BTW the territory ids are
```
732,
763,
795,
827,
920
```
for all four eureka territories and bozja.

**Comment by SheepGoMeh** [comment]
This will cause issues with various aoe markers and field mechanics, so it will not be considered.
