### ISSUE TITLE
Expand voidlist to hide player's name entirely

### ISSUE THREAD

**Issue by Naixatloz** [SheepGoMeh/VisibilityPlugin#30]
There's a person in this game I do not want to see **any trace of**. Even though I have them blacklisted and voidlisted, I can still see their name in certain contexts, such as:

- Market sales history
- House owner list when using residential district aethernet
- Message book comments
- Signature on crafted items

Is it at all feasible to hide their name in these menus? Or even better, replace it with some randomized filler name so it's not a conspicuous blank space that reminds me they exist.

**Comment by SheepGoMeh** [comment]
I'm afraid that this goes beyond the scope of the project, so the short answer here would be `no`.
