### ISSUE TITLE
Translations in PRs being ignored

### ISSUE THREAD

**Issue by Lynnea1320** [SheepGoMeh/VisibilityPlugin#31]
Just wondering if you look at the PRs.

**Comment by SheepGoMeh** [comment]
You can contribute to the translation over at https://crowdin.com/project/visibility

**Comment by Lynnea1320** [comment]
Okay do I have to wait for you to add Swedish as a language before I can
start or am I just not seeing how to add a language?

**Comment by SheepGoMeh** [comment]
Added Swedish language to Crowdin.
You will need an account to submit translations.

**Comment by Lynnea1320** [comment]
Okay I did it.
