### ISSUE TITLE
Won't work unless reinstalled each log in

### ISSUE THREAD

**Issue by drejjmit** [SheepGoMeh/VisibilityPlugin#32]
For me it doesn't work unless i reinstall the Plugin each login.
Pressing **Hide All Pets** doesn't hide them. Same with **Enable** or **Refresh**. 
Only way to get it to work is to **Disable + Install** it each time. 
Is it loading too early during login?

**Comment by SheepGoMeh** [comment]
I'm not able to replicate this nor have others so it's likely something specific to your setup. I'll keep an eye out for similar reports in the future.

**Comment by redeven** [comment]
I'm having the same issue currently. Started probably 6.15 or 6.11. Doesn't work at all unless I disable and reenable the entire plugin from the plugins list.

**Comment by drejjmit** [comment]
> I'm having the same issue currently. Started probably 6.15 or 6.11. Doesn't work at all unless I disable and reenable the entire plugin from the plugins list.

I left the Dalamud beta by removing my ``DalamudBetaKey`` from my ``dalamudConfig.json``.
Haven't noticed any issues since. 
Seems to be a Dalamud beta issue, not a plugin issue

**Comment by SheepGoMeh** [comment]
> > I left the _Dalamud beta_ by removing my `DalamudBetaKey` from my `dalamudConfig.json`. Haven't noticed any issues since. Seems to be a _Dalamud beta_ issue, not a plugin issue
> 
> Definitely not my issue then as that field is null.

As many have stated, this is not an issue with plugin.
I recommend going to the Discord (https://discord.gg/3NMcUV5) and asking for help there.
