### ISSUE TITLE
pets arent being hidden

### ISSUE THREAD

**Issue by LilyMinaj** [SheepGoMeh/VisibilityPlugin#37]
i refreshed and even reinstalled visibility but after the current patch smn pets arent being hidden for me.

**Comment by SheepGoMeh** [comment]
Pets can no longer be hidden inside duties

**Comment by LilyMinaj** [comment]
Oh really? Sorry i didn't know that.thanks for reply. Why is that though?
God I hate it lol

**Comment by SheepGoMeh** [comment]
It breaks a lot of things, so it's best not to mess with it
