### ISSUE TITLE
Custom emotes not affected by VoidList

### ISSUE THREAD

**Issue by bui** [SheepGoMeh/VisibilityPlugin#39]
While most forms of chat are successfully hidden when a player is added to VoidList, it appears that custom emote messages (/em) don't get hidden. I couldn't discern whether this is intentional or not through the code, so wanted to report it here.

**Comment by SheepGoMeh** [comment]
Custom emote messages should be handled here https://github.com/SheepGoMeh/VisibilityPlugin/blob/f8bcfdc62f717b17a13fa715cf62af6abc1c7193/Visibility/VisibilityPlugin.cs#L578

**Comment by SheepGoMeh** [comment]
Closed due to lack of updates
