### ISSUE TITLE
Command to turn visibility on and off

### ISSUE THREAD

**Issue by Mireiawen** [SheepGoMeh/VisibilityPlugin#4]
Would it be possible to get a command, for example `/pvis toggle` that enables and disables the visibility. The functionality should be same as setting the "Enable" in the visibility UI. Possibly doing the refresh as well, or having that as extra.

**Comment by SheepGoMeh** [comment]
This command already exists.
Type `/pvis help` to get more information.

**Comment by Mireiawen** [comment]
As far as I know, and the help itself shows, I can toggle any category, such as pets, chocobos etc, but I can't turn the whole plugin Enable on or off. 

```/pvis help - This help menu
/pvis <setting> <on/off/toggle> - Sets a setting to on, off or toggles it
Available values:
hidepet
hidestar
hideplayer
showcompanypet
showcompanyplayer
showcompanychocobo
showpartypet
showpartyplayer
showpartychocobo
showfriendpet
showfriendplayer
showfriendchocobo
showdeadplayer```

Either that option is not in the help, or does not exist. Or that I can't make a good guess out of the option names.

![image](https://user-images.githubusercontent.com/11092031/114858166-c869fb00-9df1-11eb-8bb4-2eacdae82011.png)
I hope this image works and shows what I am looking for.
