### ISSUE TITLE
Chinese server is not word in backlist

### ISSUE THREAD

**Issue by SaltFish-X** [SheepGoMeh/VisibilityPlugin#42]
黑名单:'宇宙和音' 不是合法的服务器名.
Blacklist: 'Cosmic Harmony' is not a legitimate server name.

宇宙和音 is a Chinese server

**Comment by SheepGoMeh** [comment]
Please refer to the CN fork maintained by @LittleNightmare at https://github.com/LittleNightmare/VisibilityPlugin
