### ISSUE TITLE
Feature Request: Setting to enable auto-void on blacklist

### ISSUE THREAD

**Issue by ghost** [SheepGoMeh/VisibilityPlugin#44]
_I didn't see this in the README, or as a past issue, but if I missed it and it already exists, I apologize. The below, I believe, would be an `enhancement`._

```
As a Player...
  who has 1 or more other players on their Blacklist
I would like a setting in the GUI...
  that can be toggled via checkbox

Which allows all Players on my Blacklist to be auto-voided (made invisible)
```

Use case:

A User is currently managing a blacklist, and a void list. To make this a bit easier for the User, it would be nice to make this a "1 stop shop". A setting to allow any and all blacklisted players to be auto-voided would be advantageous, I believe. 

_Lame visual example_

☑️ Auto-void Blacklisted Players

or

🟦 Auto-void Blacklisted Players

Note:

I'm a JavaScript/Ruby dev. I'd like to take a stab at this but have some questions regarding testing, etc. (Never worked on an addon before)

**Comment by SheepGoMeh** [comment]
This feature is no longer required as VoidList is getting deprecated.
