### ISSUE TITLE
Improvements ideias

### ISSUE THREAD

**Issue by allandiego** [SheepGoMeh/VisibilityPlugin#48]
Hello, I have 2 improvements ideias that I think shouldn't be too difficult to implement:
1 - make the gui window resizable
2 - add text command to enable / disable the visibility something like /pvis on /pvis off

**Comment by SheepGoMeh** [comment]
1. I don't see the need to resize the window, as it scales with your global font scale
2. `/pvis help` provides you with all the possible settings. The one you're most likely looking for is `/pvis enabled toggle`

**Comment by allandiego** [comment]
Oh nice, didnt noticed the help commands ty!
The resize option was because If you resize your game window with the bardtoolbox the plugins interfaces wont scale down, but with the macro I dont need the GUI anymore :D
