### ISSUE TITLE
all online players are added to whitelist ?

### ISSUE THREAD

**Issue by maxusxtreme** [SheepGoMeh/VisibilityPlugin#50]
v1.1.4.8

Each time i start the game, i see the whole whitelist being filled with all the players of the datacenter.
I tried removing the configfile and uninstall , install the plugin.
After restart of the game this happens again. the file is filled with over 60k of lines and around few MB big. Manually removing all the people one by one is a no-go.

This results in alot people being shown after hiding players, since they are on this whitelist.

**Comment by SheepGoMeh** [comment]
Could you describe a reliable method of reproducing this bug?
Step by step, as detailed as possible.

**Comment by maxusxtreme** [comment]
1. Yes.
2. I deleted playertrack config + plugin.
- deleted Visibility.json. 
- started ffxiv logged in
- no adding of 60k lines of ppl
- toggled some settings in your plugin so the Visibility.json is created.
- exit ffxiv , restarted it and logged in
- no adding of 60k lines of ppl

Conclusion the combination of that plugin is a nogo.

For me, your plugin is more important. Im closing this issue. Thanks for pointing me in the right direction.
