### ISSUE TITLE
Feature Request: Hide people of an FC

### ISSUE THREAD

**Issue by StoiaCode** [SheepGoMeh/VisibilityPlugin#52]
Hey hey! 
I heard some people wanting this before and recently grew a reason to use it myself; A functionality where I can add a FC name or Tag and everyone with that FC Tag will automatically get hidden. 
Not sure how easy it is to implement, but does that sound reasonable? Would be REALLY useful to me and some friends :)

**Comment by SheepGoMeh** [comment]
FC tag matchin is too vague as duplicates are allowed.
It will not be implemented due to that reason.

**Comment by StoiaCode** [comment]
The colored FC name tag disagrees. Whatever.
