### ISSUE TITLE
Feature request: hide non-party alliance members during raid

### ISSUE THREAD

**Issue by serin-delaunay** [SheepGoMeh/VisibilityPlugin#54]
I had hoped to use this plugin to reduce sensory overload in alliance raids by hiding the players from other alliances (and reducing the perceived alliance to a more manageable 8 with battle effects off), but during a test run I encountered two problems:
* Within the raid instance, nothing I changed in the plugin settings could hide the friends who formed the other parties, including voidlisting them individually. This may be due to setting changes during duties being ignored or the plugin having no effect during duties.
* Afterwards outside the raid instance, plugin setting changes worked as expected but the setting to show or hide party members was applied to all three parties in the alliance, which would not help with my intended use case even if the first problem was fixed. 

I haven't run further tests since they require two friends to cooperate in standing around while I use party finder and queue them into duties, but if the option to hide players from other parties in an alliance could be added and could function inside a duty instance I would appreciate it a lot.

**Comment by SheepGoMeh** [comment]
The plugin will not work in duties that have combat, as it will cause far too many issues.
I can only recommend that you tinker with the game's settings and player name options to resolve stimulus overload.

**Comment by serin-delaunay** [comment]
OK, Thanks for the quick response. I have of course already tried removing alliance nameplates and healthbars and disabling all party effects, hence wanting a more extreme option.
