### ISSUE TITLE
Feature Request: Hide players based on character configuration

### ISSUE THREAD

**Issue by jmpnul** [SheepGoMeh/VisibilityPlugin#55]
The builtin RMT message blocking with dalamud is pretty good. But it doesn't hide the bots from teleporting in and being an obvious eyesore. They all seem to be configured the exact same way (I'm guessing the default options in the character creator). It would be nice if we could hide players based on matching an exact configuration, since very few actual players created their character without at least messing with the height slider or something. Obviously there might be some casualties, but that should be up to the user to decide and be aware of.

Maybe there could be some integration with Glamourer or something, where you can create a profile for players to hide based on if they match a design set in Glamourer. It would also make it a cinch to update in future if the bots catch on, and make a modification to their character.

Thanks for the very useful plugin ^_^

**Comment by SheepGoMeh** [comment]
This feature is not planned any time soon.
