### ISSUE TITLE
Bug: Emotes To Self sfx still plays for voidlisted players

### ISSUE THREAD

**Issue by pictochatting** [SheepGoMeh/VisibilityPlugin#56]
Steps to reproduce: 
1. Void someone
2. Have them emote at you with their emote log turned on
3. Emotes To Self (Character Config > Log Window Settings > Notification Sounds) still fires and plays sound effect even though chat message is filtered.

**Comment by SheepGoMeh** [comment]
Does that happen in a duty or outside?

**Comment by SheepGoMeh** [comment]
Stale issue
