### ISSUE TITLE
Player not on list, but plugin says it is. known troll and can't poof him.

### ISSUE THREAD

**Issue by RTKH68** [SheepGoMeh/VisibilityPlugin#6]
is there a cache or something I can clear? there was a player that was harassing people nearly three whole hours but I couldn't thanos snap them out of existence, it kept saying "That Player is Already on the list" or something to that effect---they very clearly were not.

**Comment by SheepGoMeh** [comment]
1. Was the incident in a duty?
2. Are you certain that you didn't also add them to the whitelist?
3. Could you check and see if they're in the configuration file list? (Located in `%AppData%\XIVLauncher\pluginConfigs\Visibility.json`)

**Comment by RTKH68** [comment]
it wasn't in a duty, I doublechecked whitelist (it's empty, didn't even know it was a thing. what's that DO exactly? I'm not quite sure) just now, they're not there either. found the configuration file, it's not in there either.

**Comment by SheepGoMeh** [comment]
Have you restarted the client? (Maybe even the computer)

**Comment by RTKH68** [comment]
yes and yes

**Comment by SheepGoMeh** [comment]
7cb72eb4aaee2933544c5114291dbe3e6e7bd92b should fix this.
The fix should be applied in version 1.0.4.2

**Comment by RTKH68** [comment]
at the risk of sounding dumb, ....how do I install the changes? I just use XIVquicklauncher.

**Comment by SheepGoMeh** [comment]
An update will be available when it gets reviewed and merged, usually within a day or two.

**Comment by RTKH68** [comment]
oooooh ok. thanks for all your help, friend. sorry to bug you like this, be safe out there!
