### ISSUE TITLE
Can't see menu

### ISSUE THREAD

**Issue by rainvine** [SheepGoMeh/VisibilityPlugin#61]
I tried all sorts of different things- reinstalling, recalibrating... Nadda. 
I type /pvis 
and it does not put up the menu, 

I click settings button in the dalamud plugin window of visibility, and it doesn't pop the menu up. 

Thanks for the help please let me know if it gets fixed =)

**Comment by SheepGoMeh** [comment]
Please look at the pinned issue #11
