### ISSUE TITLE
Not working at all in dungeons

### ISSUE THREAD

**Issue by Raikao9** [SheepGoMeh/VisibilityPlugin#65]
Just queued into a dungeon, put someone on voidlist. And it didn't work. They still showed up. Why?

**Comment by SheepGoMeh** [comment]
That is intentional.
This will not work in duties.

**Comment by Raikao9** [comment]
What? Why? I literally wasn't able to use it for it's purpose of removing a player who I had blacklisted already.

**Comment by Multidayz** [comment]
This plug in is amazing, testing out today. Was hoping you could reconsider it not being able to work in Duties though. I was excited to go into Eureka/Bozja with it and found it did not work at all. The lag with additional players is really bad in these places and being able to turn off all the additional items really makes the whole experience enjoyable. Thank you for your time though on it!

**Comment by SheepGoMeh** [comment]
The plugin will not work in duties that have combat, as it will cause far too many issues.

**Comment by Xelfen** [comment]
I'd also like a partial function for this (just make the characters invisible, still clickable), I hope it'll be possible later. support against unfairly assigned negative emotes

**Comment by PrincessRTFM** [comment]
Hi. I'm one of Sheep's collaborator's, and a plugin developer myself. The answer they gave was very clear, but apparently not quite clear _enough_, so let me try too now:

No. It will not happen. It is never going to be added. The requested feature has been considered and refused. The plugin will not do that. It is not an option. That will not be done.

Aside from the very simple reason of "you are in combat with those people and should be able to see them", which is the reason for the "unfairly assigned negative emotes", there are also technical reasons involving the game's engine which make it non-viable to actually implement.

Not one but _two_ developers have spoken. The request has been clearly denied. If you are in an instance with someone you would rather not be around, _leave the instance_.
