### ISSUE TITLE
Voidlisting doesn't stay

### ISSUE THREAD

**Issue by OmegaJackie** [SheepGoMeh/VisibilityPlugin#66]
I'm having an issue where the voidlist refuses to accept new entries and

https://github.com/SheepGoMeh/VisibilityPlugin/assets/115854606/8d3abdcf-cbe0-4728-9ee0-c0fe21fdb2af

 will wipe itself when I get out of render range.

**Comment by SheepGoMeh** [comment]
Please disable all plugins and try again.
If the problem still persists, it is a Visibility issue.
Otherwise, it is most likely one of your other plugins, possibly even third party plugins.

**Comment by SheepGoMeh** [comment]
There have no updates on the issue, as such it is stale and will be closed.
