### ISSUE TITLE
Voidtarget not working for me

### ISSUE THREAD

**Issue by kajsle** [SheepGoMeh/VisibilityPlugin#75]
It worked fine before Dawntrail, now it does nothing for me. I have added people to the list and they do not disappear, I only get a message they were added in the chat but they are still visible to me like I did nothing (I tested all this in open world and cities where it worked before). My whitelist is empty btw.

_Newbie to github here, and I never reported a problem with ffxiv mods so sorry if it lacks any potential logs or info._

**Comment by PrincessRTFM** [comment]
Voidlist has been deprecated in favour of the newly-added vanilla feature to do the same thing. The plugin's functionality was complicated, used string comparisons which are very expensive at this level, and was a source of significant frustration and a number of (mostly user-fault) problems. It is no longer supported, the functionality has been disabled, and it will not be returning in the future.

**Comment by kajsle** [comment]
Thank you for the info! very sad to hear that as ingame list is limited and it's not possible to just target someone and block, but totally understandable!
