### ISSUE TITLE
Suggestion: Hide by race

### ISSUE THREAD

**Issue by hiromell** [SheepGoMeh/VisibilityPlugin#89]
Hello, would it be possible to make an hide function by specific race, or hide everyone except selected race

**Comment by SheepGoMeh** [comment]
That kind of feature is outside the scope of the intended feature list and will not be implemented.

**Comment by ToxicStar8** [comment]
I needed this feature, so I created a 'BlockAnyRace' plugin in my DalamudPlugins by studying this plugin.

[repositorie](https://github.com/ToxicStar8/DalamudPlugins/)
